# Generated by Django 4.2.4 on 2023-09-15 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prjct_Name', models.CharField(max_length=50, verbose_name='Estimate Project Name')),
                ('due_date', models.DateField(verbose_name='Due Date(YYYY-MM-DD)')),
                ('status', models.CharField(choices=[('On Hold', 'On Hold'), ('Working', 'Working'), ('Complete', 'Complete')], default='Working', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start Date(YYYY-MM-DD)')),
                ('bid_amount', models.IntegerField(verbose_name='Bid Amount')),
                ('bidder', models.CharField(max_length=1500, null=True, verbose_name='bidder ')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.company', verbose_name='Company')),
                ('estimator', models.ForeignKey(limit_choices_to=models.Q(('roles__name', 'Estimator')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations_as_estimator', to=settings.AUTH_USER_MODEL, verbose_name='Estimator')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Location Name')),
            ],
        ),
        migrations.CreateModel(
            name='Proposals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Proposel Date(YYYY-MM-DD)')),
                ('architect_name', models.CharField(max_length=50, verbose_name='Architect Name')),
                ('architect_firm', models.CharField(max_length=50, verbose_name='Architect Firm')),
                ('estimating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estimating.estimating')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255, verbose_name='Add Qualification')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=250, verbose_name='add Serves(INCLUSIONS or EXCLUSIONS)')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_name', models.CharField(max_length=250, verbose_name='Specification Name')),
                ('budget', models.IntegerField(verbose_name='Budget')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estimating.proposals')),
            ],
        ),
        migrations.CreateModel(
            name='Spec_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Add Number')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('sefic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estimating.specification', verbose_name='Specification')),
            ],
        ),
        migrations.CreateModel(
            name='PropsalsServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceTyp', models.CharField(choices=[('Exclusions', 'Exclusions'), ('Inclusions', 'Inclusions')], default='Exclusions', max_length=50, verbose_name='Service Type')),
                ('propsals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estimating.proposals', verbose_name='Proposals')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estimating.service', verbose_name='Add service')),
            ],
        ),
        migrations.CreateModel(
            name='Estimating_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prnt_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Folder Parent ID')),
                ('drctry_name', models.CharField(max_length=255, verbose_name='Folder Name')),
                ('file_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type Name')),
                ('output_Table_Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='file Name')),
                ('file_field', models.FileField(null=True, upload_to='Files/')),
                ('file_binary_data', models.BinaryField(blank=True, null=True)),
                ('Estimating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estimating.estimating', verbose_name='Add Estimating')),
            ],
        ),
        migrations.AddField(
            model_name='estimating',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Estimating.location'),
        ),
        migrations.CreateModel(
            name='Addendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Addendum Date(YYYY-MM-DD)')),
                ('addendum_Number', models.IntegerField(verbose_name='Addendum Number')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estimating.proposals')),
            ],
        ),
    ]
