# Generated by Django 4.2.4 on 2023-09-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propsalsservices',
            name='serviceTyp',
            field=models.CharField(choices=[('Exclusions', 'Exclusions'), ('Inclusions', 'Inclusions')], default='Exclusion', max_length=50),
        ),
    ]
