# Generated by Django 4.2.4 on 2023-09-21 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimating_detail',
            name='prnt_id',
        ),
        migrations.AddField(
            model_name='estimating_detail',
            name='prnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Estimating.estimating_detail', verbose_name='Folder Parent ID'),
        ),
        migrations.AlterField(
            model_name='estimating_detail',
            name='Estimating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimating_details', to='Estimating.estimating', verbose_name='Add Estimating'),
        ),
        migrations.AlterField(
            model_name='estimating_detail',
            name='drctry_name',
            field=models.CharField(blank=True, default='Default Value', max_length=255, null=True, verbose_name='Folder Name'),
        ),
    ]
