# Generated by Django 4.2.4 on 2023-09-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimating',
            name='timezone',
            field=models.CharField(blank=True, choices=[('PDT', 'Pacific Daylight Time'), ('CT', 'Central Time'), ('PST', 'Pacific Standard Time')], default='PDT', max_length=3, null=True, verbose_name='Time Zone'),
        ),
    ]
