# Generated by Django 4.2.4 on 2023-09-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimating',
            name='status',
            field=models.CharField(choices=[('On Hold', 'On Hold'), ('Working', 'Working'), ('Complete', 'Complete')], default='Working', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='propsalsservices',
            name='serviceTyp',
            field=models.CharField(choices=[('Exclusions', 'Exclusions'), ('Inclusions', 'Inclusions')], default='Exclusions', max_length=50, verbose_name='Service Type'),
        ),
    ]
