# Generated by Django 4.2.4 on 2023-09-08 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Estimating', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimating',
            old_name='estmate_Prjct_Name',
            new_name='Prjct_Name',
        ),
        migrations.RemoveField(
            model_name='estimating',
            name='Areas',
        ),
        migrations.RemoveField(
            model_name='estimating',
            name='PST',
        ),
        migrations.RemoveField(
            model_name='estimating',
            name='link',
        ),
        migrations.RemoveField(
            model_name='estimating',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='estimating',
            name='reviwed',
        ),
        migrations.RemoveField(
            model_name='estimating',
            name='start_date',
        ),
        migrations.AddField(
            model_name='estimating',
            name='users',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('roles__name__in', ['Estimator', 'Bidder'])), to=settings.AUTH_USER_MODEL),
        ),
    ]
