# Generated by Django 4.2.4 on 2023-09-19 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addendum',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Addendums', to='Estimating.proposal'),
        ),
        migrations.AlterField(
            model_name='proposalservice',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Estimating.proposal'),
        ),
        migrations.AlterField(
            model_name='spec_detail',
            name='number',
            field=models.CharField(max_length=8, verbose_name='Add Number'),
        ),
        migrations.AlterField(
            model_name='spec_detail',
            name='sefic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sefic', to='Estimating.specification', verbose_name='Specification'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spcifc', to='Estimating.proposal'),
        ),
    ]
