# Generated by Django 4.2.4 on 2023-09-08 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Estimating', '0002_rename_estmate_prjct_name_estimating_prjct_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Location')),
            ],
        ),
        migrations.RemoveField(
            model_name='estimating',
            name='users',
        ),
        migrations.AddField(
            model_name='estimating',
            name='bidder',
            field=models.ForeignKey(limit_choices_to=models.Q(('roles__name', 'Bidder')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations_as_bidder', to=settings.AUTH_USER_MODEL, verbose_name='Bidder'),
        ),
        migrations.AddField(
            model_name='estimating',
            name='estimator',
            field=models.ForeignKey(limit_choices_to=models.Q(('roles__name', 'Estimator')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations_as_estimator', to=settings.AUTH_USER_MODEL, verbose_name='Estimator'),
        ),
        migrations.AlterField(
            model_name='estimating',
            name='due_date',
            field=models.DateField(null=True, verbose_name='Due Date(YYYY-MM-DD)'),
        ),
        migrations.AddField(
            model_name='estimating',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Estimating.location'),
        ),
    ]
