# Generated by Django 4.2.4 on 2023-09-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0002_remove_estimating_detail_prnt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimating_detail',
            name='drctry_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Folder Name'),
        ),
        migrations.AlterField(
            model_name='estimating_detail',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='temporary_files/'),
        ),
    ]
