# Generated by Django 4.2.4 on 2023-09-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0002_alter_estimating_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimating',
            name='timezone',
            field=models.CharField(blank=True, choices=[('PDT', 'PDT'), ('CT', 'CT'), ('PST', 'PST')], default='PDT', max_length=3, null=True, verbose_name='Time Zone'),
        ),
    ]
