# Generated by Django 4.2.4 on 2023-09-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0002_alter_urlstable_ps'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimating',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Add link'),
        ),
    ]
