# Generated by Django 4.2.4 on 2023-09-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0003_alter_estimating_detail_drctry_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimating_detail',
            name='file_field',
        ),
    ]
