# Generated by Django 4.2.4 on 2023-09-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0003_location_remove_estimating_users_estimating_bidder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimating',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='start Date(YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='estimating',
            name='status',
            field=models.CharField(choices=[(' ', ' '), ('On Hold', 'On Hold'), ('Working', 'Working'), ('Complete', 'Complete')], default=' ', max_length=50),
        ),
    ]
