# Generated by Django 4.2.4 on 2023-10-02 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Estimating', '0003_estimating_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimating',
            name='estimator',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_active', True), ('roles__name', 'Estimator')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations_as_estimator', to=settings.AUTH_USER_MODEL, verbose_name='Estimator'),
        ),
    ]
