# Generated by Django 4.2.4 on 2023-09-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0004_estimating_start_date_alter_estimating_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimating',
            name='due_date',
            field=models.DateTimeField(null=True, verbose_name='Due Date(YYYY-MM-DD)'),
        ),
    ]
