# Generated by Django 4.2.4 on 2023-10-02 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0005_company_is_active_alter_estimating_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='estimating',
            name='bid_amount',
            field=models.IntegerField(verbose_name='Bid Amount '),
        ),
        migrations.AlterField(
            model_name='estimating',
            name='location',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_active', True)), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimating_as_Area', to='Estimating.location', verbose_name='Add Area'),
        ),
    ]
