# Generated by Django 4.2.4 on 2023-10-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0007_alter_estimating_prjct_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimating',
            name='Prjct_Name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Estimate Project Name'),
        ),
        migrations.AlterField(
            model_name='estimating',
            name='bidder_deatil',
            field=models.CharField(max_length=5000, null=True, verbose_name='Bidder Detail'),
        ),
    ]
