# Generated by Django 4.2.4 on 2023-10-03 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0008_alter_estimating_prjct_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimating',
            old_name='Prjct_Name',
            new_name='prjct_name',
        ),
    ]
