# Generated by Django 4.2.4 on 2023-10-05 19:57

import Estimating.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0009_rename_prjct_name_estimating_prjct_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Cmpny_Name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='adress',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fax_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', validators=[Estimating.validation.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='company',
            name='office_phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
