# Generated by Django 4.2.4 on 2023-10-12 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0013_remove_estimating_bidder_deatil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dprtmnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dprtmnt_name', models.CharField(max_length=250, verbose_name='Add the department name ')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Role')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Add Description')),
            ],
        ),
        migrations.CreateModel(
            name='DMS_Dertory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email')),
                ('direct_number', models.IntegerField(blank=True, null=True, verbose_name='Direct')),
                ('locaton', models.CharField(blank=True, max_length=250, null=True, verbose_name='Location')),
                ('mobile_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Estimating.company', verbose_name='company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Estimating.dprtmnt', verbose_name='Department ')),
                ('jon_title', models.ManyToManyField(blank=True, to='Estimating.role', verbose_name='Role')),
            ],
        ),
    ]
