# Generated by Django 4.2.4 on 2023-10-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0019_rename_bidder_address_estimating_bidder_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimating',
            name='bidder_detail',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Bidder Detail'),
        ),
    ]
