# Generated by Django 4.2.4 on 2023-10-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0020_alter_estimating_bidder_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='plane_date',
            field=models.DateField(null=True, verbose_name='Plane Date(YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='estimating',
            name='timezone',
            field=models.CharField(blank=True, choices=[('PDT', 'PDT'), ('CT', 'CT'), ('EST', 'EST')], max_length=3, null=True, verbose_name='PST'),
        ),
    ]
