# Generated by Django 4.2.4 on 2023-10-23 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0021_proposal_plane_date_alter_estimating_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='estimating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Estimating.estimating'),
        ),
    ]
