# Generated by Django 4.2.4 on 2023-10-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0023_remove_dms_dertory_job_title_dms_dertory_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='plane_date',
        ),
        migrations.AddField(
            model_name='estimating',
            name='plane_date',
            field=models.DateField(null=True, verbose_name='Plane Date(YYYY-MM-DD)'),
        ),
    ]
