# Generated by Django 4.2.4 on 2023-11-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0024_remove_proposal_plane_date_estimating_plane_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimating',
            name='plane_date',
            field=models.DateField(blank=True, null=True, verbose_name='Plane Date(YYYY-MM-DD)'),
        ),
    ]
