# Generated by Django 4.2.4 on 2023-11-24 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0025_alter_estimating_plane_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dms_dertory',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.CreateModel(
            name='GC_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc_name', models.CharField(blank=True, max_length=1500, null=True, verbose_name='GC Name')),
                ('gc_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='GC Email')),
                ('gc_detail', models.CharField(blank=True, max_length=1500, null=True, verbose_name='GC Detail')),
                ('estimating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Estimating.estimating')),
            ],
        ),
    ]
