# Generated by Django 4.2.4 on 2023-11-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0027_alter_estimating_status_alter_gc_detail_estimating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimating',
            name='plane_date',
        ),
        migrations.AddField(
            model_name='proposal',
            name='plane_date',
            field=models.DateField(blank=True, null=True, verbose_name='Plane Date(YYYY-MM-DD)'),
        ),
    ]
