# Generated by Django 4.2.4 on 2023-12-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0032_alter_estimating_bid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='adress',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Address'),
        ),
    ]
