# Generated by Django 4.2.4 on 2024-01-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0038_delete_qualification_remove_proposalservice_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255, verbose_name='Add Qualification')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estimating.proposal')),
            ],
        ),
    ]
