# Generated by Django 4.2.4 on 2024-01-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0039_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='Estimating.proposal'),
        ),
    ]
