# Generated by Django 4.2.4 on 2024-01-10 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0041_alter_estimating_estimator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addendum',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Addendums', to='Estimating.proposal'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='Estimating.proposal'),
        ),
        migrations.AlterField(
            model_name='spec_detail',
            name='sefic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sefic', to='Estimating.specification', verbose_name='Specification'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spcifc', to='Estimating.proposal'),
        ),
    ]
