# Generated by Django 4.2.4 on 2024-02-14 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0042_alter_addendum_proposal_alter_qualification_proposal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedLogoCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(blank=True, max_length=250, null=True, verbose_name='Type of Attachment')),
                ('binary', models.BinaryField(blank=True, editable=True, null=True, verbose_name='Atthd_pdf')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Estimating.company', verbose_name='Select Company')),
            ],
        ),
    ]
