# Generated by Django 4.2.4 on 2024-02-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0043_attachedlogocompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimating',
            name='important_active',
            field=models.BooleanField(default=True),
        ),
    ]
