# Generated by Django 4.2.4 on 2024-02-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0045_alter_estimating_important_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addendum',
            name='addendum_Number',
            field=models.IntegerField(null=True, verbose_name='Addendum Number'),
        ),
    ]
