# Generated by Django 4.2.4 on 2023-09-12 14:55

import accounts.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Role')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Add Description')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_Name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('signtrPDF', models.FileField(blank=True, null=True, upload_to='user_pdfs/', validators=[accounts.validation.validate_pdf_file_extension])),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='accounts.userrole', verbose_name='Role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
