# Generated by Django 4.2.4 on 2023-10-05 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0009_rename_prjct_name_estimating_prjct_name'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='Estimating.company', verbose_name='company'),
            preserve_default=False,
        ),
    ]
