# Generated by Django 4.2.4 on 2023-09-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Role')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Add Description')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='accounts.userrole', verbose_name='Role'),
        ),
    ]
