# Generated by Django 4.2.4 on 2023-09-12 12:26

import accounts.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='signtrImage',
        ),
        migrations.AddField(
            model_name='user',
            name='signtrPDF',
            field=models.FileField(blank=True, null=True, upload_to='user_pdfs/', validators=[accounts.validation.validate_pdf_file_extension]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
