# Generated by Django 4.2.4 on 2023-10-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_department_user_direct_number_user_locaton_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Role'),
        ),
    ]
