# Generated by Django 4.2.4 on 2023-11-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signtr',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
