# Generated by Django 4.2.4 on 2023-11-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_signtr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='signtr',
        ),
    ]
