# Generated by Django 4.2.4 on 2023-09-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlstable',
            name='ps',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
