# Generated by Django 4.2.4 on 2023-10-02 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0004_alter_estimating_estimator'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estimating',
            name='company',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_active', True)), on_delete=django.db.models.deletion.CASCADE, related_name='company_in_estimator', to='Estimating.company', verbose_name='Company'),
        ),
    ]
