# Generated by Django 4.2.4 on 2023-10-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0011_alter_company_cmpny_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimating',
            name='bidder_mail',
            field=models.EmailField(default=1, max_length=254, verbose_name='add the bidder Mail'),
            preserve_default=False,
        ),
    ]
