# Generated by Django 4.2.4 on 2023-10-12 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0014_dprtmnt_role_dms_dertory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dms_dertory',
            old_name='jon_title',
            new_name='job_title',
        ),
    ]




