# Generated by Django 4.2.4 on 2023-10-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0016_remove_estimating_bidder_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dms_dertory',
            name='last_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
