# Generated by Django 4.2.4 on 2023-10-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0017_dms_dertory_lat_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dms_dertory',
            old_name='full_Name',
            new_name='first_name',
        ),
    ]
