# Generated by Django 4.2.4 on 2023-11-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0028_remove_estimating_plane_date_proposal_plane_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
