# Generated by Django 4.2.4 on 2023-12-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0031_alter_specification_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimating',
            name='bid_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Bid Amount '),
        ),
    ]
