# Generated by Django 4.2.4 on 2024-01-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0034_alter_estimating_estimator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimating',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='estimating',
            name='bidder_detail',
        ),
        migrations.RemoveField(
            model_name='estimating',
            name='bidder_mail',
        ),
        migrations.AddField(
            model_name='gc_detail',
            name='gc_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GC Number'),
        ),
        migrations.AlterField(
            model_name='estimating',
            name='location',
            field=models.CharField(default='California', max_length=250, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='estimating',
            name='timezone',
            field=models.CharField(blank=True, choices=[('MST', 'MST'), ('CST', 'CST'), ('EST', 'EST'), ('PST', 'PST')], max_length=3, null=True, verbose_name='Time zone'),
        ),
    ]
