# Generated by Django 4.2.4 on 2024-02-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0044_estimating_important_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimating',
            name='important_active',
            field=models.BooleanField(default=False),
        ),
    ]
