# Generated by Django 4.2.4 on 2024-03-07 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0082_delete_wagerateproject'),
        ('reports', '0002_wageratedetail_remove_wagerate_area_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wageratedetail',
            name='area_name',
        ),
        migrations.RemoveField(
            model_name='wageratedetail',
            name='title',
        ),
        migrations.AddField(
            model_name='wageratedetail',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='add project'),
        ),
        migrations.AddField(
            model_name='wageratedetail',
            name='titleName',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Title name'),
        ),
        migrations.DeleteModel(
            name='WageRate',
        ),
    ]
