# Generated by Django 4.2.4 on 2024-03-07 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0079_alter_addmoreinstance_instancevalue'),
        ('reports', '0002_wageratedetail_remove_wagerate_area_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wageratedetail',
            old_name='area_name',
            new_name='title_name',
        ),
        migrations.AddField(
            model_name='wagerate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='add project'),
        ),
    ]
