# Generated by Django 4.2.4 on 2023-10-14 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0015_rename_jon_title_dms_dertory_job_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_project_forman_project_bim_oprtr_project_estimating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='job_name',
        ),
        migrations.AddField(
            model_name='project',
            name='Spec',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Not Available', max_length=50, null=True, verbose_name="Spec's per our Scope"),
        ),
        migrations.AddField(
            model_name='project',
            name='addendums',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Not Available', max_length=50, null=True, verbose_name='Addendum'),
        ),
        migrations.AddField(
            model_name='project',
            name='bid',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Not Available', max_length=50, null=True, verbose_name='bid'),
        ),
        migrations.AddField(
            model_name='project',
            name='contacts',
            field=models.CharField(blank=True, choices=[('On build', 'On build'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='Contacts'),
        ),
        migrations.AddField(
            model_name='project',
            name='drywell',
            field=models.CharField(blank=True, choices=[('Submited', 'Submited'), ('Working', 'Working'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='Drywell Conttrol Joins'),
        ),
        migrations.AddField(
            model_name='project',
            name='finish',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Working', 'Working'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='FINISH LEVEL MARKUPS'),
        ),
        migrations.AddField(
            model_name='project',
            name='general_superintendent',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('roles__name', 'General Superintendent'), ('roles__name', 'So. Cal. General Manager'), ('roles__name', 'No. Cal. General Manager'), ('roles__name', 'President'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Genral_superintendent'),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Working', 'Working'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='PROGRESS TRACKING'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_address',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Add project address'),
        ),
        migrations.AddField(
            model_name='project',
            name='ro_door',
            field=models.CharField(blank=True, choices=[('Working', 'Working'), ('Submited', 'Submited'), ('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=50, null=True, verbose_name='RO-Door'),
        ),
        migrations.AddField(
            model_name='project',
            name='ro_window',
            field=models.CharField(blank=True, choices=[('Working', 'Working'), ('Submited', 'Submited'), ('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=50, null=True, verbose_name='RO-Window'),
        ),
        migrations.AddField(
            model_name='project',
            name='scop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Estimating.spec_detail', verbose_name='Add scope of Work'),
        ),
        migrations.AddField(
            model_name='project',
            name='substitution',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Substitution'),
        ),
        migrations.AddField(
            model_name='project',
            name='wall_type',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Working', 'Working'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='WALL TYPE MAPPING'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Forman',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('roles__name', 'Foreman'), ('roles__name', 'General Superintendent'), ('roles__name', 'So. Cal. General Manager'), ('roles__name', 'No. Cal. General Manager'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Forman_as_Forman', to=settings.AUTH_USER_MODEL, verbose_name='FOREMAN/Superintendent'),
        ),
        migrations.CreateModel(
            name='Zlien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zlien', models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='Zlien')),
                ('date', models.DateField(blank=True, null=True, verbose_name='add date(YYYY-MM-DD)')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='add project')),
            ],
        ),
        migrations.CreateModel(
            name='Submittals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='Submittals')),
                ('date', models.DateField(blank=True, null=True, verbose_name='add date(YYYY-MM-DD)')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='add project')),
                ('scop_work_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Estimating.spec_detail', verbose_name='Add scope of Work')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Contractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Capable', 'Capable'), ('Not Capable', 'Not Capable'), ('Custom', 'Custom')], default='Not Capable', max_length=50, null=True, verbose_name='Sub Contractors')),
                ('date', models.DateField(blank=True, null=True, verbose_name='add date(YYYY-MM-DD)')),
                ('comment_box', models.CharField(blank=True, max_length=5000, null=True, verbose_name='comment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='add project')),
            ],
        ),
        migrations.CreateModel(
            name='Sov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Aproved', 'Aproved'), ('Pending', 'Pending'), ('Custom', 'Custom')], default='Pending', max_length=50, null=True, verbose_name='Labor Rate')),
                ('date', models.DateField(blank=True, null=True, verbose_name='add date if Status Approved (YYYY-MM-DD)')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='add project')),
            ],
        ),
        migrations.CreateModel(
            name='ShopDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='Shop Drawing')),
                ('date', models.DateField(blank=True, null=True, verbose_name='add date(YYYY-MM-DD)')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='add project')),
                ('scop_work_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Estimating.spec_detail', verbose_name='Add scope of Work')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_of_Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='Schedule of Value')),
                ('schedule_date', models.DateField(blank=True, null=True, verbose_name='add date of the schedule if Approved (YYYY-MM-DD)')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='add project')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Not Available', max_length=50, null=True, verbose_name='Schedule')),
                ('date', models.DateField(blank=True, null=True, verbose_name='add date(YYYY-MM-DD)')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='add project')),
            ],
        ),
        migrations.CreateModel(
            name='Safity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='Safity')),
                ('date', models.DateField(blank=True, null=True, verbose_name='add date(YYYY-MM-DD)')),
                ('comment_box', models.CharField(max_length=5000, verbose_name='comment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='add project')),
                ('scop_work_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Estimating.spec_detail', verbose_name='Add scope of Work')),
            ],
        ),
        migrations.CreateModel(
            name='OnBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, choices=[('Addendum', 'Addendum'), ('Bide Proposal', 'Bide Proposal'), ('Specs', 'Specs'), ('Contract', 'Contract'), ('Submitile', 'Submitile'), ('Safety', 'Safety'), ('Shop Drawing', 'Shop Drawing'), ('Budget', 'Budget')], max_length=50, null=True, verbose_name='select field for the On Build')),
                ('status', models.CharField(blank=True, choices=[('Uploade', 'Uploade'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='HDS System')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='add project')),
            ],
        ),
        migrations.CreateModel(
            name='LaborRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Aproved', 'Aproved'), ('Pending', 'Pending'), ('Custom', 'Custom')], default='Pending', max_length=50, null=True, verbose_name='Labor Rate')),
                ('date', models.DateField(blank=True, null=True, verbose_name='add date(YYYY-MM-DD)')),
                ('comment_box', models.CharField(blank=True, max_length=5000, null=True, verbose_name='comment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='add project')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance', models.CharField(blank=True, choices=[('CCIP', 'CCIP'), ('Sent', 'Sent'), ('Received', 'Received'), ('Complete', 'Complete')], default='null', max_length=50, null=True, verbose_name='Insurance')),
                ('date', models.DateField(blank=True, null=True, verbose_name='add date(YYYY-MM-DD)')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='add project')),
            ],
        ),
        migrations.CreateModel(
            name='HDS_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Not Required', 'Not Required'), ('Aproved', 'Aproved'), ('Pending', 'Pending'), ('Custom', 'Custom')], default='Pending', max_length=50, null=True, verbose_name='HDS System')),
                ('date', models.DateField(blank=True, null=True, verbose_name='add date(YYYY-MM-DD)')),
                ('comment_box', models.CharField(blank=True, max_length=5000, null=True, verbose_name='comment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='add project')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(blank=True, choices=[('Fully Executed', 'Fully Executed'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='Contract')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='add date of the Contract if Fully Executed (YYYY-MM-DD)')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='add project')),
            ],
        ),
        migrations.CreateModel(
            name='Buget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Custom', 'Custom')], default='Pending', max_length=50, null=True, verbose_name='Labor Rate')),
                ('comment_box', models.CharField(blank=True, max_length=5000, null=True, verbose_name='comment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='add project')),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond', models.CharField(blank=True, choices=[('Sent', 'Sent'), ('Received', 'Received'), ('Complete', 'Complete')], default='null', max_length=50, null=True, verbose_name='Bond')),
                ('date', models.DateField(blank=True, null=True, verbose_name='add date(YYYY-MM-DD)')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='add project')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='add due date(YYYY-MM-DD)')),
                ('reduction', models.CharField(blank=True, max_length=500, null=True, verbose_name='Add Reduction')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='add project')),
            ],
        ),
    ]
