# Generated by Django 4.2.4 on 2023-10-14 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0015_rename_jon_title_dms_dertory_job_title'),
        ('projects', '0005_remove_project_scop_alter_project_estimating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safity',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Estimating.proposal', verbose_name='Add scope of Work'),
        ),
        migrations.AddField(
            model_name='shopdrawing',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Estimating.proposal', verbose_name='Add scope of Work'),
        ),
        migrations.AddField(
            model_name='submittals',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Estimating.proposal', verbose_name='Add scope of Work'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Estimating.proposal', verbose_name='Add scope of Work'),
        ),
    ]
