# Generated by Django 4.2.4 on 2023-10-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_scope_alter_safity_proposal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sov',
            name='status',
            field=models.CharField(blank=True, choices=[('Aproved', 'Aproved'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='Labor Rate'),
        ),
    ]
