# Generated by Django 4.2.4 on 2023-10-26 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0024_remove_proposal_plane_date_estimating_plane_date'),
        ('projects', '0014_remove_safity_proposal_remove_shopdrawing_proposal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safity',
            name='comment_box',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='submittals',
            name='scop_work_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scop_work_number', to='Estimating.spec_detail', verbose_name='Add scope of Work'),
        ),
    ]
