# Generated by Django 4.2.4 on 2023-10-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_safity_scop_work_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safity',
            name='scopWorkNumber',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Add the scop of work Number'),
        ),
        migrations.AddField(
            model_name='shopdrawing',
            name='scopWorkNumber',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Add the scop of work Number'),
        ),
        migrations.AddField(
            model_name='submittals',
            name='scopWorkNumber',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Add the scop of work Number'),
        ),
    ]
