# Generated by Django 4.2.4 on 2023-12-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_delete_schedule_of_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onbuild',
            name='project',
        ),
        migrations.RemoveField(
            model_name='sov',
            name='project',
        ),
        migrations.RemoveField(
            model_name='zlien',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Spec',
        ),
        migrations.RemoveField(
            model_name='project',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='project',
            name='progress',
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.DeleteModel(
            name='OnBuild',
        ),
        migrations.DeleteModel(
            name='Sov',
        ),
        migrations.DeleteModel(
            name='Zlien',
        ),
    ]
