# Generated by Django 4.2.4 on 2023-12-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_remove_delay_notice_gc_forem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delay_notice',
            name='close_date',
        ),
        migrations.RemoveField(
            model_name='delay_notice',
            name='open_date',
        ),
        migrations.AddField(
            model_name='rfi',
            name='close_date',
            field=models.DateField(blank=True, null=True, verbose_name='date Closed'),
        ),
        migrations.AddField(
            model_name='rfi',
            name='open_date',
            field=models.DateField(blank=True, null=True, verbose_name='date Opened'),
        ),
        migrations.AddField(
            model_name='rfi',
            name='other_trd',
            field=models.BooleanField(default=1, verbose_name='Other Trades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfi',
            name='rply_by',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Reply By'),
        ),
        migrations.AddField(
            model_name='rfi',
            name='rspns',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Response'),
        ),
        migrations.CreateModel(
            name='PCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('attn', models.CharField(blank=True, max_length=500, null=True, verbose_name='Attn')),
                ('company', models.CharField(blank=True, max_length=500, null=True, verbose_name='Company')),
                ('addrs', models.CharField(blank=True, max_length=500, null=True, verbose_name='Address')),
                ('pco_num', models.CharField(blank=True, max_length=500, null=True, verbose_name='PCO NO.')),
                ('dcrsbsn', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description of work')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project')),
            ],
        ),
        migrations.AddField(
            model_name='delay_notice',
            name='pco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.pco', verbose_name='PCO'),
        ),
    ]
