# Generated by Django 4.2.4 on 2023-12-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_remove_delay_notice_close_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfi',
            name='other_trd',
            field=models.BooleanField(blank=True, null=True, verbose_name='Other Trades'),
        ),
    ]
