# Generated by Django 4.2.4 on 2023-12-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_alter_rfi_other_trd'),
    ]

    operations = [
        migrations.AddField(
            model_name='pco',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='pco',
            name='zip_city',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='City,Zip code'),
        ),
    ]
