# Generated by Django 4.2.4 on 2023-12-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_pco_email_pco_zip_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pco',
            name='zip_city',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='City,Stat,Zip code'),
        ),
    ]
