# Generated by Django 4.2.4 on 2024-01-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_rename_other_trd_rfi_bool1_remove_project_gc_pm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='bond',
            field=models.CharField(blank=True, choices=[('Sent', 'Sent'), ('Received', 'Received'), ('Completed', 'Completed'), ('N/A', 'N/A'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='Bond'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance',
            field=models.CharField(blank=True, choices=[('CCIP', 'CCIP'), ('Sent', 'Sent'), ('Received', 'Received'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='Insurance'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Requested', 'Requested'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='submittals',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Working', 'Working'), ('Submitted', 'Submitted'), ('R & R', 'R & R'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='Submittals'),
        ),
    ]
