# Generated by Django 4.2.4 on 2024-01-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_alter_bond_bond_alter_insurance_insurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='drywell',
            field=models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Working', 'Working'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='Drywell Conttrol Joins'),
        ),
        migrations.AlterField(
            model_name='project',
            name='finish',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Working', 'Working'), ('Uploaded', 'Uploaded'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='FINISH LEVEL MARKUPS'),
        ),
        migrations.AlterField(
            model_name='project',
            name='wall_type',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Working', 'Working'), ('Uploaded', 'Uploaded'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='WALL TYPE MAPPING'),
        ),
    ]
