# Generated by Django 4.2.4 on 2024-01-10 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_alter_project_drywell_alter_project_finish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFI_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc_rfi_num', models.IntegerField(blank=True, null=True, verbose_name='GC RFI#')),
                ('date_close', models.DateField(blank=True, null=True, verbose_name='Date close')),
                ('status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Close', 'Close'), ('Void', 'Void')], default='Close', max_length=50, null=True, verbose_name='Status')),
                ('dscrptn', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Description')),
                ('cost_schdl', models.CharField(blank=True, choices=[('Cost', 'Cost'), ('Schedule', 'Schedule'), ('Cost & Schedule', 'Cost & Schedule'), ('None', 'None')], default='None', max_length=50, null=True, verbose_name='Cost or Schedule')),
                ('rfi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.rfi', verbose_name='Select RFI')),
            ],
        ),
    ]
