# Generated by Django 4.2.4 on 2024-01-26 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_remove_pco_addrs_remove_pco_attn_remove_pco_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pco',
            name='zip_city',
        ),
        migrations.AddField(
            model_name='pco',
            name='asi_num',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ASI NO.'),
        ),
        migrations.AddField(
            model_name='pco',
            name='atchd_pdf',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Atthd_pdf'),
        ),
        migrations.AddField(
            model_name='pco',
            name='chnge_dtals',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Change Detail'),
        ),
        migrations.AddField(
            model_name='pco',
            name='cost_ohp_mtrl_tax',
            field=models.FloatField(blank=True, null=True, verbose_name='value of Cost + OH&P + Material tax'),
        ),
        migrations.AddField(
            model_name='pco',
            name='get_bond',
            field=models.FloatField(blank=True, null=True, verbose_name='Bond@'),
        ),
        migrations.AddField(
            model_name='pco',
            name='get_ohp_tax',
            field=models.FloatField(blank=True, null=True, verbose_name='Enter the OH&P @'),
        ),
        migrations.AddField(
            model_name='pco',
            name='get_tax',
            field=models.FloatField(blank=True, null=True, verbose_name='Material Tax'),
        ),
        migrations.AddField(
            model_name='pco',
            name='lbr_totl',
            field=models.FloatField(blank=True, null=True, verbose_name='Labor Total'),
        ),
        migrations.AddField(
            model_name='pco',
            name='mscllns_totl',
            field=models.FloatField(blank=True, null=True, verbose_name='Miscellaneous Total'),
        ),
        migrations.AddField(
            model_name='pco',
            name='mtrl_sub_totl',
            field=models.FloatField(blank=True, null=True, verbose_name='Material Sub total '),
        ),
        migrations.AddField(
            model_name='pco',
            name='mtrl_totl',
            field=models.FloatField(blank=True, null=True, verbose_name='Material Total'),
        ),
        migrations.AddField(
            model_name='pco',
            name='pci_num',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ACI NO.'),
        ),
        migrations.AddField(
            model_name='pco',
            name='rfi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.rfi', verbose_name='Add RFI'),
        ),
        migrations.AddField(
            model_name='pco',
            name='subtotl_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Subtotal Cost'),
        ),
        migrations.AddField(
            model_name='pco',
            name='totl_rqest',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Req'),
        ),
        migrations.AddField(
            model_name='pco',
            name='typ',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Type of PCO'),
        ),
        migrations.AddField(
            model_name='pco',
            name='value_bond',
            field=models.FloatField(blank=True, null=True, verbose_name='Value of Bond'),
        ),
        migrations.AddField(
            model_name='pco',
            name='value_ohp_tax',
            field=models.FloatField(blank=True, null=True, verbose_name='value of OH&P @'),
        ),
        migrations.AddField(
            model_name='pco',
            name='value_tax',
            field=models.FloatField(blank=True, null=True, verbose_name='Material Tax'),
        ),
        migrations.AddField(
            model_name='pco',
            name='work_day',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estimating Working day'),
        ),
        migrations.AlterField(
            model_name='delay_log',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=50, null=True, verbose_name='Select status'),
        ),
        migrations.AlterField(
            model_name='delay_log',
            name='typ',
            field=models.CharField(blank=True, choices=[('Related PCO', 'Related PCO'), ('Related RFI', 'Related RFI'), ('Other Trades', 'Other Trades')], default='Other Traders', max_length=50, null=True, verbose_name='Select status'),
        ),
        migrations.AlterField(
            model_name='pco',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Current Date'),
        ),
        migrations.AlterField(
            model_name='pco',
            name='dcrsbsn',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='PCO Description'),
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255, verbose_name='Add Qualification')),
                ('pco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.pco', verbose_name='PCO')),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itm_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Material item name')),
                ('quntty', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('unit', models.CharField(blank=True, max_length=500, null=True, verbose_name='Unit')),
                ('unit_prz', models.FloatField(blank=True, null=True, verbose_name='Unit$')),
                ('totl', models.FloatField(blank=True, null=True, verbose_name='Total')),
                ('pco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.pco', verbose_name='PCO')),
            ],
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itm_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Material item name')),
                ('quntty', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('unit', models.CharField(blank=True, max_length=500, null=True, verbose_name='Unit')),
                ('unit_prz', models.FloatField(blank=True, null=True, verbose_name='Unit$')),
                ('totl', models.FloatField(blank=True, null=True, verbose_name='Total')),
                ('pco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.pco', verbose_name='PCO')),
            ],
        ),
        migrations.CreateModel(
            name='Debited_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itm_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Material item name')),
                ('quntty', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('unit', models.CharField(blank=True, max_length=500, null=True, verbose_name='Unit')),
                ('unit_prz', models.FloatField(blank=True, null=True, verbose_name='Unit$')),
                ('totl', models.FloatField(blank=True, null=True, verbose_name='Total')),
                ('pco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.pco', verbose_name='PCO')),
            ],
        ),
        migrations.CreateModel(
            name='Credited_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itm_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Material item name')),
                ('quntty', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('unit', models.CharField(blank=True, max_length=500, null=True, verbose_name='Unit')),
                ('unit_prz', models.FloatField(blank=True, null=True, verbose_name='Unit$')),
                ('totl', models.FloatField(blank=True, null=True, verbose_name='Total')),
                ('pco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.pco', verbose_name='PCO')),
            ],
        ),
    ]
