# Generated by Django 4.2.4 on 2024-01-26 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_remove_pco_zip_city_pco_asi_num_pco_atchd_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pco',
            name='rfi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.rfi_log', verbose_name='Add RFI'),
        ),
    ]
