# Generated by Django 4.2.4 on 2024-01-27 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_pco_prpd_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCO_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_m', models.CharField(blank=True, max_length=50, null=True, verbose_name='T&M')),
                ('cor_amont', models.FloatField(blank=True, null=True, verbose_name='Cor Amount')),
                ('co_amont', models.FloatField(blank=True, null=True, verbose_name='C/O Amount')),
                ('co_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='C/O#')),
                ('uthr_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Author Name')),
                ('note', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Note')),
                ('pco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.pco', verbose_name='PCO')),
            ],
        ),
    ]
