# Generated by Django 4.2.4 on 2024-02-06 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_alter_credited_material_pco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delay_notice',
            name='atchd_pdf',
        ),
        migrations.RemoveField(
            model_name='pco',
            name='atchd_pdf',
        ),
        migrations.RemoveField(
            model_name='rfi',
            name='atchd_pdf',
        ),
        migrations.CreateModel(
            name='Attached_Pdf_Rfi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binary', models.BinaryField(blank=True, editable=True, null=True, verbose_name='Atthd_pdf')),
                ('typ', models.CharField(blank=True, max_length=250, null=True, verbose_name='Type of Attachment')),
                ('rfi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.rfi', verbose_name='Select RFI')),
            ],
        ),
        migrations.CreateModel(
            name='Attached_Pdf_Pco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binary', models.BinaryField(blank=True, editable=True, null=True, verbose_name='Atthd_pdf')),
                ('typ', models.CharField(blank=True, max_length=250, null=True, verbose_name='Type of Attachment')),
                ('pco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.pco', verbose_name='Select PCO')),
            ],
        ),
        migrations.CreateModel(
            name='Attached_Pdf_Delay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binary', models.BinaryField(blank=True, editable=True, null=True, verbose_name='Atthd_pdf')),
                ('typ', models.CharField(blank=True, max_length=250, null=True, verbose_name='Type of Attachment')),
                ('delay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.delay_notice', verbose_name='Select Delay Notice')),
            ],
        ),
    ]
