# Generated by Django 4.2.4 on 2024-02-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_attached_pdf_delay_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='important_active',
            field=models.BooleanField(default=False),
        ),
    ]
