# Generated by Django 4.2.4 on 2024-02-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0067_bond_is_active_buget_is_active_contract_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ro_window_is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='RO-Window active'),
        ),
    ]
