# Generated by Django 4.2.4 on 2024-02-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_project_contacts_is_active_project_drywell_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='addendums',
        ),
        migrations.AddField(
            model_name='project',
            name='addendumEnd',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Addendum End'),
        ),
        migrations.AddField(
            model_name='project',
            name='addendumStart',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Addendum Start'),
        ),
    ]
