# Generated by Django 4.2.4 on 2024-02-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0070_remove_project_addendums_project_addendumend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bonds_is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Bonds active'),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Budget active'),
        ),
        migrations.AddField(
            model_name='project',
            name='contracts_is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Contracts active'),
        ),
        migrations.AddField(
            model_name='project',
            name='hdsSystem_is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='HDS System active'),
        ),
        migrations.AddField(
            model_name='project',
            name='insurances_is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Insurances active'),
        ),
        migrations.AddField(
            model_name='project',
            name='scheduleOfValue_is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Schedule of value active'),
        ),
        migrations.AddField(
            model_name='project',
            name='schedule_is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Schedule active'),
        ),
        migrations.AddField(
            model_name='project',
            name='subContractors_is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Sub Contractors active'),
        ),
        migrations.AddField(
            model_name='project',
            name='wageRate_is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Wage Rate active'),
        ),
        migrations.AlterField(
            model_name='project',
            name='finish',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Working', 'Working'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='FINISH LEVEL MARKUPS'),
        ),
        migrations.AlterField(
            model_name='project',
            name='wall_type',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Working', 'Working'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='WALL TYPE MAPPING'),
        ),
    ]
