# Generated by Django 4.2.4 on 2024-02-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_project_bonds_is_active_project_budget_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfi',
            name='detl_num',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Detail No'),
        ),
    ]
