# Generated by Django 4.2.4 on 2024-03-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0077_addmoreinstance_instancevalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgingproject',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='addmoreinstance',
            name='instanceName',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='New Name'),
        ),
        migrations.AlterField(
            model_name='addmoreinstance',
            name='instanceValue',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='badgingproject',
            name='firstName',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='badgingproject',
            name='lastName',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Late Name'),
        ),
        migrations.AlterField(
            model_name='badgingproject',
            name='middle',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Midle'),
        ),
        migrations.AlterField(
            model_name='badgingproject',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Phone'),
        ),
    ]
