# Generated by Django 4.2.4 on 2024-03-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0078_badgingproject_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmoreinstance',
            name='instanceValue',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Value'),
        ),
    ]
