# Generated by Django 4.2.4 on 2024-03-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0080_wagerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='delay_notice',
            name='building',
            field=models.CharField(blank=True, max_length=520, null=True, verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='delay_notice',
            name='room',
            field=models.CharField(blank=True, max_length=520, null=True, verbose_name='Room'),
        ),
    ]
