# Generated by Django 4.2.4 on 2024-03-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0082_delay_log_unresolveddelaydays'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittals',
            name='LastUpdated_Date',
            field=models.DateField(blank=True, null=True, verbose_name='add LastUpdated_Date(YYYY-MM-DD)'),
        ),
    ]
