# Generated by Django 4.2.4 on 2024-03-25 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0083_submittals_lastupdated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('tmNumber', models.CharField(blank=True, max_length=250, null=True, verbose_name='T&M #')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(blank=True, max_length=250, null=True, verbose_name='Item Name')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('tm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.tm', verbose_name='select T&M')),
            ],
        ),
        migrations.CreateModel(
            name='LaborTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creaftMan', models.CharField(blank=True, max_length=250, null=True, verbose_name='Craft Man')),
                ('hours', models.FloatField(blank=True, null=True, verbose_name='Hours')),
                ('tm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.tm', verbose_name='select T&M')),
            ],
        ),
    ]
