# Generated by Django 4.2.4 on 2024-03-25 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0084_tm_material_labortm'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscellaneousTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(blank=True, max_length=250, null=True, verbose_name='Item Name')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('tm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.tm', verbose_name='select T&M')),
            ],
        ),
        migrations.CreateModel(
            name='Attached_Pdf_TM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binary', models.BinaryField(blank=True, editable=True, null=True, verbose_name='Atthd_pdf')),
                ('typ', models.CharField(blank=True, max_length=250, null=True, verbose_name='Type of Attachment')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='File Name')),
                ('tm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.tm', verbose_name='Select T&M')),
            ],
        ),
    ]
