# Generated by Django 4.2.4 on 2023-09-27 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Estimating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_num', models.PositiveIntegerField(verbose_name='Add Job Number')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start Date(YYYY-MM-DD)')),
                ('Forman', models.ForeignKey(limit_choices_to=models.Q(('roles__name', 'Forman')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Forman_as_Forman', to=settings.AUTH_USER_MODEL, verbose_name='Forman\t')),
                ('bim_oprtr', models.ForeignKey(limit_choices_to=models.Q(('roles__name', 'Bim Operator')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Bim_Operator', to=settings.AUTH_USER_MODEL, verbose_name='Bim Operator')),
                ('estimating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estimating.estimating', verbose_name='Estimating')),
                ('prjct_engnr', models.ForeignKey(limit_choices_to=models.Q(('roles__name', 'Project Engineer')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_Engineer', to=settings.AUTH_USER_MODEL, verbose_name='Project Engineer')),
                ('prjct_mngr', models.ForeignKey(limit_choices_to=models.Q(('roles__name', 'Project Manager')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_Manager', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager')),
            ],
        ),
        migrations.CreateModel(
            name='Project_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drctry_Name', models.CharField(max_length=255, verbose_name='Folder Name')),
                ('file_type', models.CharField(max_length=100, null=True, verbose_name='Type Name')),
                ('file_name', models.CharField(max_length=100, null=True, verbose_name='file Name')),
                ('file_binary_data', models.BinaryField(blank=True, null=True)),
                ('prjct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project')),
                ('prnt_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.project_detail', verbose_name='Folder Parent ID')),
            ],
        ),
    ]
