# Generated by Django 4.2.4 on 2023-09-12 14:55

from django.db import migrations, models
import django.db.models.deletion
import projects.validation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cmpny_Name', models.CharField(max_length=50, verbose_name='Company Name')),
                ('adress', models.CharField(max_length=70, verbose_name='Adress')),
                ('office_phone_number', models.CharField(max_length=10)),
                ('fax_number', models.CharField(max_length=10)),
                ('license_number', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logos/', validators=[projects.validation.validate_file_extension])),
                ('email', models.EmailField(default='estimating@dmsmgt.com', editable=False, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prjct_Name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.company')),
            ],
        ),
        migrations.CreateModel(
            name='Project_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drctry_Name', models.CharField(max_length=255, verbose_name='Folder Name')),
                ('prnt_ID', models.PositiveIntegerField(verbose_name='Folder Parent ID')),
                ('file_Name', models.CharField(max_length=100, verbose_name='File Name')),
                ('output_Table_Name', models.CharField(max_length=100, verbose_name='Table Name')),
                ('prjct_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project')),
            ],
        ),
    ]
