# Generated by Django 4.2.4 on 2023-09-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Cmpny_Name',
            field=models.CharField(max_length=255, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prjct_Name',
            field=models.CharField(max_length=255, verbose_name='Project Name'),
        ),
    ]
