# Generated by Django 4.2.4 on 2023-10-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Forman',
        ),
        migrations.RemoveField(
            model_name='project',
            name='bim_oprtr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='estimating',
        ),
        migrations.RemoveField(
            model_name='project',
            name='job_num',
        ),
        migrations.RemoveField(
            model_name='project',
            name='prjct_engnr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='prjct_mngr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
