# Generated by Django 4.2.4 on 2023-09-08 14:13

from django.db import migrations, models
import projects.validation


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_company_cmpny_name_alter_project_prjct_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='adress',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Adress'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='estimating@dmsmgt.com', max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='fax_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', validators=[projects.validation.validate_logo_file_extension]),
        ),
        migrations.AddField(
            model_name='company',
            name='office_phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='Cmpny_Name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Company Name'),
        ),
    ]
