# Generated by Django 4.2.4 on 2023-09-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_detail',
            name='file_name',
            field=models.CharField(max_length=100, null=True, verbose_name='file Name'),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='file_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Type Name'),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='prnt_ID',
            field=models.PositiveIntegerField(null=True, verbose_name='Folder Parent ID'),
        ),
    ]
