# Generated by Django 4.2.4 on 2023-09-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_company_adress_company_email_company_fax_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(default='estimating@dmsmgt.com', editable=False, max_length=254),
        ),
    ]
