# Generated by Django 4.2.4 on 2023-10-14 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0015_rename_jon_title_dms_dertory_job_title'),
        ('projects', '0004_remove_project_job_name_project_spec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='scop',
        ),
        migrations.AlterField(
            model_name='project',
            name='estimating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_start_date', to='Estimating.estimating', verbose_name='estimating'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Estimating.spec_detail', verbose_name='Add scope of Work'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('P', 'P'), ('Q', 'Q'), ('V', 'V'), ('X', 'X')], default='P', max_length=50, null=True),
        ),
    ]
