# Generated by Django 4.2.4 on 2023-09-27 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_detail_prnt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_detail',
            name='prnt_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.project_detail', verbose_name='Folder Parent ID'),
        ),
    ]
