# Generated by Django 4.2.4 on 2023-10-19 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_alter_sov_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='prjct_mngr',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('roles__name', 'Project Manager'), ('roles__name', 'Proconstruction Manager'), ('roles__name', 'Vice President'), ('roles__name', 'No. Cal. General Manager'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_Manager', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager'),
        ),
    ]
