# Generated by Django 4.2.4 on 2023-10-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_estimating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hds_system',
            name='status',
            field=models.CharField(blank=True, choices=[('Not Required', 'Not Required'), ('Approved', 'Approved'), ('Pending', 'Pending'), ('Custom', 'Custom')], default='Pending', max_length=50, null=True, verbose_name='HDS System'),
        ),
        migrations.AlterField(
            model_name='laborrate',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Custom', 'Custom')], default='Pending', max_length=50, null=True, verbose_name='Labor Rate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Pre-Construction', 'Pre-Construction'), ('Construction Phase', 'Construction Phase'), ('Close out phase', 'Close out phase'), ('Upcoming/Estimating pahse', 'Upcoming/Estimating pahse'), ('Complete', 'Complete')], default='Pre-Construction', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sov',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='Labor Rate'),
        ),
    ]
