# Generated by Django 4.2.4 on 2023-10-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_hds_system_status_alter_laborrate_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safity',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='shopdrawing',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='submittals',
            name='proposal',
        ),
    ]
