# Generated by Django 4.2.4 on 2023-10-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0024_remove_proposal_plane_date_estimating_plane_date'),
        ('projects', '0015_alter_safity_comment_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safity',
            name='scop_work_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scop_work_number_sfty', to='Estimating.spec_detail', verbose_name='Add scope of Work'),
        ),
        migrations.AlterField(
            model_name='shopdrawing',
            name='scop_work_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scop_work_number_shpdrg', to='Estimating.spec_detail', verbose_name='Add scope of Work'),
        ),
    ]
