# Generated by Django 4.2.4 on 2023-11-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_onbuild_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule_of_Value',
        ),
    ]
