# Generated by Django 4.2.4 on 2023-12-05 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_remove_onbuild_project_remove_sov_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_of_Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True, verbose_name='Schedule of Value')),
                ('schedule_date', models.DateField(blank=True, null=True, verbose_name='add date of the schedule if Approved (YYYY-MM-DD)')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='add project')),
            ],
        ),
    ]
