# Generated by Django 4.2.4 on 2023-12-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_schedule_of_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittals',
            old_name='date',
            new_name='actn_date',
        ),
        migrations.RemoveField(
            model_name='safity',
            name='scop_work_number',
        ),
        migrations.RemoveField(
            model_name='shopdrawing',
            name='scop_work_number',
        ),
        migrations.RemoveField(
            model_name='submittals',
            name='scop_work_number',
        ),
        migrations.AddField(
            model_name='submittals',
            name='dscrptn',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Add Description'),
        ),
        migrations.AddField(
            model_name='submittals',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='add date(YYYY-MM-DD)'),
        ),
        migrations.AddField(
            model_name='submittals',
            name='gc_dcsn',
            field=models.CharField(blank=True, choices=[('Accepted By GC', 'Accepted By GC'), ('Rejected By GC', 'Rejected By GC')], default='Rejected By GC', max_length=500, null=True, verbose_name='GC Decision'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='bond',
            field=models.CharField(blank=True, choices=[('Sent', 'Sent'), ('Received', 'Received'), ('Complete', 'Complete'), ('N/A', 'N/A')], default='null', max_length=50, null=True, verbose_name='Bond'),
        ),
        migrations.AlterField(
            model_name='buget',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Save', 'Save')], default='Pending', max_length=50, null=True, verbose_name='Labor Rate'),
        ),
        migrations.AlterField(
            model_name='hds_system',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='HDS System'),
        ),
        migrations.AlterField(
            model_name='laborrate',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Labor Rate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='addendums',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Addendum'),
        ),
        migrations.AlterField(
            model_name='project',
            name='drywell',
            field=models.CharField(blank=True, choices=[('Submited', 'Submited'), ('Working', 'Working'), ('Approved', 'Approved')], default='null', max_length=50, null=True, verbose_name='Drywell Conttrol Joins'),
        ),
        migrations.AlterField(
            model_name='project',
            name='finish',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Working', 'Working'), ('Uploaded', 'Uploaded')], default='null', max_length=50, null=True, verbose_name='FINISH LEVEL MARKUPS'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ro_door',
            field=models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Pending', 'Pending'), ('Received', 'Received')], default='Pending', max_length=50, null=True, verbose_name='RO-Door'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ro_window',
            field=models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Pending', 'Pending'), ('Received', 'Received')], default='Pending', max_length=50, null=True, verbose_name='RO-Window'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Pre-Construction', 'Pre-Construction'), ('Construction Phase', 'Construction Phase'), ('Close out phase', 'Close out phase'), ('Upcoming/Estimating phase', 'Upcoming/Estimating phase'), ('Complete', 'Complete')], default='Pre-Construction', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='wall_type',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Working', 'Working'), ('Uploaded', 'Uploaded')], default='null', max_length=50, null=True, verbose_name='WALL TYPE MAPPING'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Requested', 'Requested')], default='Requested', max_length=50, null=True, verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='sub_contractors',
            name='status',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Sub Contractors'),
        ),
        migrations.AlterField(
            model_name='submittals',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Working', 'Working'), ('Submitted', 'Submitted'), ('R & R', 'R & R')], max_length=50, null=True, verbose_name='Submittals'),
        ),
    ]
