# Generated by Django 4.2.4 on 2023-12-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_rename_date_submittals_actn_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='drywell',
            field=models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Working', 'Working'), ('Approved', 'Approved')], default='null', max_length=50, null=True, verbose_name='Drywell Conttrol Joins'),
        ),
    ]
