# Generated by Django 4.2.4 on 2023-12-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_project_drywell'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_contractors',
            name='custom',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='If Custom'),
        ),
    ]
