# Generated by Django 4.2.4 on 2023-12-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_sub_contractors_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='hds_system',
            name='custom',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='If Custom'),
        ),
        migrations.AddField(
            model_name='laborrate',
            name='custom',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='If Custom'),
        ),
    ]
