# Generated by Django 4.2.4 on 2023-12-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_hds_system_custom_laborrate_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfi_num', models.IntegerField(blank=True, null=True, verbose_name='RFI #')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('attn', models.CharField(blank=True, max_length=500, null=True, verbose_name='Attn')),
                ('company', models.CharField(blank=True, max_length=500, null=True, verbose_name='Company')),
                ('phne', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('drwng_rfrnc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Drawing Reference')),
                ('detl_num', models.IntegerField(blank=True, null=True, verbose_name='Detail No')),
                ('spc_rfrnc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Spec Reference')),
                ('rspns_rqrd', models.CharField(blank=True, max_length=500, null=True, verbose_name='Response Required By')),
                ('qustn', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Question')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Select')),
            ],
        ),
    ]
