# Generated by Django 4.2.4 on 2023-12-13 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0030_alter_spec_detail_number'),
        ('projects', '0026_delay_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delay_notice',
            name='delay_num',
            field=models.IntegerField(blank=True, default=1, verbose_name='Delay Number #'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delay_notice',
            name='gnrl_cntrctr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Estimating.gc_detail', verbose_name='General Contractor'),
        ),
    ]
