# Generated by Django 4.2.4 on 2023-12-14 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0030_alter_spec_detail_number'),
        ('projects', '0027_delay_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delay_notice',
            name='gc_forem',
        ),
        migrations.RemoveField(
            model_name='delay_notice',
            name='gnrl_cntrctr',
        ),
        migrations.AddField(
            model_name='project',
            name='gc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Estimating.gc_detail', verbose_name='Add GC'),
        ),
        migrations.AddField(
            model_name='project',
            name='gc_address',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='GC Address'),
        ),
        migrations.AddField(
            model_name='project',
            name='gc_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GC Phone number'),
        ),
        migrations.AddField(
            model_name='project',
            name='gc_pm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GC Super/PM'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='rfi_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RFI #'),
        ),
    ]
