# Generated by Django 4.2.4 on 2023-12-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_alter_pco_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='bond',
            field=models.CharField(blank=True, choices=[('Sent', 'Sent'), ('Received', 'Received'), ('Completed', 'Completed'), ('N/A', 'N/A')], default='null', max_length=50, null=True, verbose_name='Bond'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance',
            field=models.CharField(blank=True, choices=[('CCIP', 'CCIP'), ('Sent', 'Sent'), ('Received', 'Received'), ('Completed', 'Completed')], default='null', max_length=50, null=True, verbose_name='Insurance'),
        ),
    ]
