# Generated by Django 4.2.4 on 2024-01-08 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0038_delete_qualification_remove_proposalservice_service_and_more'),
        ('projects', '0034_alter_bond_bond_alter_insurance_insurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='gc_phone',
        ),
        migrations.AlterField(
            model_name='project',
            name='Forman',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('job_title__name', 'Foreman'), ('job_title__name', 'General Superintendent'), ('job_title__name', 'So. Cal. General Manager'), ('job_title__name', 'No. Cal. General Manager'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Forman_as_Forman', to='Estimating.dms_dertory', verbose_name='FOREMAN/Superintendent'),
        ),
        migrations.AlterField(
            model_name='project',
            name='bim_oprtr',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('job_title__name', 'BIM'), ('job_title__name', 'BIM Modeler/Trimble Operator'), ('job_title__name', 'BIM/Manager PR'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Bim_Operator', to='Estimating.dms_dertory', verbose_name='BIM Modeler'),
        ),
        migrations.AlterField(
            model_name='project',
            name='general_superintendent',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('job_title__name', 'General Superintendent'), ('job_title__name', 'So. Cal. General Manager'), ('job_title__name', 'No. Cal. General Manager'), ('job_title__name', 'President'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='Estimating.dms_dertory', verbose_name='Genral_superintendent'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prjct_engnr',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('job_title__name', 'Project Engineer')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_Engineer', to='Estimating.dms_dertory', verbose_name='Project Engineer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prjct_mngr',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('job_title__name', 'Project Manager'), ('job_title__name', 'Proconstruction Manager'), ('job_title__name', 'Vice President'), ('job_title__name', 'No. Cal. General Manager'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_Manager', to='Estimating.dms_dertory', verbose_name='Project Manager'),
        ),
    ]
