# Generated by Django 4.2.4 on 2024-01-11 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_rfi_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delay_notice',
            name='Asocatd_rfi',
        ),
        migrations.RemoveField(
            model_name='delay_notice',
            name='if_yes_rfi',
        ),
        migrations.RemoveField(
            model_name='delay_notice',
            name='pco',
        ),
        migrations.AddField(
            model_name='delay_notice',
            name='rfi_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.rfi_log', verbose_name='RFI log'),
        ),
        migrations.AddField(
            model_name='rfi_log',
            name='received_date',
            field=models.DateField(blank=True, null=True, verbose_name='Received Date'),
        ),
        migrations.AlterField(
            model_name='delay_notice',
            name='delay_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Delay Number #'),
        ),
        migrations.AlterField(
            model_name='rfi_log',
            name='gc_rfi_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GC RFI#'),
        ),
    ]
