# Generated by Django 4.2.4 on 2024-01-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_delay_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfi',
            name='atchd_pdf',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Atthd_pdf'),
        ),
    ]
