# Generated by Django 4.2.4 on 2024-01-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_remove_delay_log_dely_log_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfi_log',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Close', 'Close'), ('Void', 'Void')], default='Open', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
