# Generated by Django 4.2.4 on 2024-01-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_alter_rfi_log_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pco',
            name='addrs',
        ),
        migrations.RemoveField(
            model_name='pco',
            name='attn',
        ),
        migrations.RemoveField(
            model_name='pco',
            name='company',
        ),
        migrations.RemoveField(
            model_name='pco',
            name='email',
        ),
        migrations.RemoveField(
            model_name='rfi_log',
            name='dscrptn',
        ),
        migrations.AddField(
            model_name='delay_notice',
            name='atchd_pdf',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Atthd_pdf'),
        ),
        migrations.AddField(
            model_name='rfi',
            name='dscrptn',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Description'),
        ),
    ]
