# Generated by Django 4.2.4 on 2024-01-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_alter_pco_rfi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pco',
            name='prpd_by',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Login User name'),
        ),
    ]
