# Generated by Django 4.2.4 on 2024-01-27 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_pco_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='delay_notice',
            name='pco_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.pco_log', verbose_name='PCO'),
        ),
    ]
