# Generated by Django 4.2.4 on 2024-01-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_rfi_log_project_alter_qualification_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pco_log',
            old_name='uthr_name',
            new_name='auther_name',
        ),
    ]
