# Generated by Django 4.2.4 on 2024-02-04 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_alter_credited_material_pco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labor',
            name='typ',
        ),
        migrations.AlterField(
            model_name='credited_material',
            name='pco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.pco', verbose_name='PCO'),
        ),
        migrations.AlterField(
            model_name='debited_material',
            name='pco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.pco', verbose_name='PCO'),
        ),
        migrations.AlterField(
            model_name='labor',
            name='pco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.pco', verbose_name='PCO'),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='pco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.pco', verbose_name='PCO'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='detail',
            field=models.CharField(max_length=255, verbose_name='Add Qualification'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='pco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.pco', verbose_name='PCO'),
        ),
    ]
