# Generated by Django 4.2.4 on 2024-02-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_remove_labor_typ_alter_credited_material_pco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='detail',
            field=models.CharField(max_length=5000, verbose_name='Add Qualification'),
        ),
    ]
