# Generated by Django 4.2.4 on 2024-02-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_remove_delay_notice_atchd_pdf_remove_pco_atchd_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Pre-Construction', 'Pre-Construction'), ('Construction Phase', 'Construction Phase'), ('Close out phase', 'Close out phase'), ('Complete', 'Complete')], default='Pre-Construction', max_length=50, null=True),
        ),
    ]
