# Generated by Django 4.2.4 on 2024-02-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_contractors',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sub_contractors',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sub Contractors Name'),
        ),
        migrations.AddField(
            model_name='sub_contractors',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number'),
        ),
    ]
