# Generated by Django 4.2.4 on 2024-02-14 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_sub_contractors_email_sub_contractors_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attached_Pdf_Rfi_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(blank=True, max_length=250, null=True, verbose_name='Type of Attachment')),
                ('binary', models.BinaryField(blank=True, editable=True, null=True, verbose_name='Atthd_pdf')),
                ('rfi_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.rfi_log', verbose_name='Select RFI_Log')),
            ],
        ),
    ]
