# Generated by Django 4.2.4 on 2024-02-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_attached_pdf_rfi_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='detail',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Add Qualification'),
        ),
    ]
