# Generated by Django 4.2.4 on 2024-02-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_alter_qualification_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='attached_pdf_delay',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='File Name'),
        ),
        migrations.AddField(
            model_name='attached_pdf_pco',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='File Name'),
        ),
        migrations.AddField(
            model_name='attached_pdf_rfi',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='File Name'),
        ),
        migrations.AddField(
            model_name='attached_pdf_rfi_log',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='File Name'),
        ),
    ]
