# Generated by Django 4.2.4 on 2024-02-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_project_important_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Important'),
        ),
        migrations.AddField(
            model_name='buget',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Important'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Important'),
        ),
        migrations.AddField(
            model_name='hds_system',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Important'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Important'),
        ),
        migrations.AddField(
            model_name='laborrate',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Important'),
        ),
        migrations.AddField(
            model_name='safity',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Important'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Important'),
        ),
        migrations.AddField(
            model_name='schedule_of_value',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Important'),
        ),
        migrations.AddField(
            model_name='shopdrawing',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Important'),
        ),
        migrations.AddField(
            model_name='sub_contractors',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Important'),
        ),
        migrations.AddField(
            model_name='submittals',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Important'),
        ),
    ]
