# Generated by Django 4.2.4 on 2024-02-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_project_ro_window_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contacts_is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='contacts active'),
        ),
        migrations.AddField(
            model_name='project',
            name='drywell_is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='drawell active'),
        ),
        migrations.AddField(
            model_name='project',
            name='finish_is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='finish active'),
        ),
        migrations.AddField(
            model_name='project',
            name='ro_door_is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ro-door active'),
        ),
        migrations.AddField(
            model_name='project',
            name='wall_type_is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='wall type active'),
        ),
    ]
