# Generated by Django 4.2.4 on 2024-02-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0072_alter_rfi_detl_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credited_material',
            name='quntty',
            field=models.FloatField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='debited_material',
            name='quntty',
            field=models.FloatField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='delay_notice',
            name='date',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='delay_notice',
            name='schdul_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Schedule ID #'),
        ),
        migrations.AlterField(
            model_name='labor',
            name='quntty',
            field=models.FloatField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='quntty',
            field=models.FloatField(blank=True, null=True, verbose_name='Quantity'),
        ),
    ]
