# Generated by Django 4.2.4 on 2024-03-06 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0076_badgingproject_addmoreinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmoreinstance',
            name='instanceValue',
            field=models.CharField(default=1, max_length=50, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addmoreinstance',
            name='badging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.badgingproject', verbose_name='select Badging'),
        ),
        migrations.AlterField(
            model_name='badgingproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='select project'),
        ),
    ]
