# Generated by Django 4.2.4 on 2024-03-07 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0079_alter_addmoreinstance_instancevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='WageRateProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Add Title')),
                ('st_amount', models.FloatField(blank=True, null=True, verbose_name='ST Amount')),
                ('ot_amount', models.FloatField(blank=True, null=True, verbose_name='OT Amount')),
                ('dt_amount', models.FloatField(blank=True, null=True, verbose_name='DT Amount')),
                ('laborRate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.laborrate', verbose_name='add Labor Rate')),
            ],
        ),
    ]
