# Generated by Django 4.2.4 on 2024-03-07 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0080_wagerateproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wagerateproject',
            name='laborRate',
        ),
        migrations.AddField(
            model_name='wagerateproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='add project'),
        ),
    ]
