# Generated by Django 4.2.4 on 2024-03-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0081_remove_wagerateproject_laborrate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WageRateProject',
        ),
    ]
