# Generated by Django 4.2.4 on 2024-03-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0081_delay_notice_building_delay_notice_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='delay_log',
            name='unResolvedDelayDays',
            field=models.IntegerField(blank=True, null=True, verbose_name='UnResolved Delay Days'),
        ),
    ]
