# Generated by Django 4.2.4 on 2024-01-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_signtr'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signtr',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
