# Generated by Django 4.2.4 on 2024-03-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BIM', '0002_alter_bim_bimrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bim',
            name='bimRequirement',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='bim',
            name='modelAvailable',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Architect Model available'),
        ),
    ]
